### ISSUE TITLE
Can't install under mantis 2.2.0 

### ISSUE THREAD

**Issue by thE-iNviNciblE** [mantisbt-plugins/CustomizeEmailSubject#5] opened 2019-04-13 13:31 UTC
i see the plugin ready to install, but if i click on "install" nothing happen.

no install, no crash.

**Comment by dregad** [comment] 2019-10-04 07:53
Duplicate of #3

**Closed** 2019-10-04 07:54 UTC
Labels: duplicate

**Comment by thE-iNviNciblE** [comment] 2020-02-09 18:20
would it be fixed?

seems still not working...

**Comment by dregad** [comment] 2020-04-13 17:18
Done now
